/*---------------------------------------------------------------------------------------
-- SOURCE FILE:             main.h
--
-- PROGRAM:                 KindaGoodProtocol
--
-- FUNCTIONS:               N/A
--
-- DATE:                    November 27, 2018
--
-- REVISIONS:               N/A
--
-- DESIGNERS:               Benny Wang
--
-- PROGRAMMERS:             Benny Wang
--
-- NOTES:
--                          The entry point of the application.
---------------------------------------------------------------------------------------*/
#include "KindaGoodProtocol.h"
#include <QtWidgets/QApplication>


/*--------------------------------------------------------------------------------------------------
-- FUNCTION:                main
--
-- DATE:                    November 27, 2018
--
-- REVISIONS:               N/A
--
-- DESIGNER:                The Qt Company
--
-- PROGRAMMER:              The Qt Company
--
-- INTERFACE:               int main(int argc, char *argv[])
--                              argc: The number of command line arguments.
--                              argv: An array of command line arguments.
--
-- NOTES:
--                          The entry point of the application. This file is auto generated by the
--                          Qt framework. The actual start of code is in the constructor of the
--                          KindaGoodProtocol class.
--------------------------------------------------------------------------------------------------*/
int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    KindaGoodProtocol w;
    w.show();
    return a.exec();
}
